AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - string-cases.gemspec
  NewCops: enable
  TargetRubyVersion: 2.7

require:
  - rubocop-performance
  - rubocop-rspec

# https://github.com/AtomLinter/linter-rubocop/issues/2
Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

# Disabled on purpose: https://github.com/bbatsov/rubocop/issues/1758
Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 160

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 25

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrivialAccessors:
  ExactNameMatch: true
  Enabled: true
